import me.modmuss50.mpp.ReleaseType

plugins {
    alias libs.plugins.fabric.loom
    id 'maven-publish'
    alias libs.plugins.lombok
    alias libs.plugins.spotless
    alias libs.plugins.modmuss50.publish
}

def targetJavaVersion = Integer.parseInt(java_version)
def local = !System.getenv().containsKey("GITHUB_RUN_NUMBER")

version = "${mod_version}+mc${minecraft_version}"
group = project.maven_group

base {
    archivesName = "${project.mod_id}-${loader_id}"
}

apply from: "https://raw.githubusercontent.com/constellation-mc/artifacts/main/artifacts.groovy"
constellationRepo(project, "pulsar")

repositories {
    exclusiveContent {
        forRepository {
            maven { url = 'https://maven.parchmentmc.org/' }
        }
        filter { includeGroup('org.parchmentmc.data') }
    }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation libs.fabric.loader

    modImplementation libs.fabric.api
    modImplementation libs.pulsar
}

spotless {
    java {
        removeUnusedImports()
        palantirJavaFormat('2.91.0').style("GOOGLE")
        trimTrailingWhitespace()
        formatAnnotations()
    }
}

loom {
    runs {
        client {
            runDirectory = file("run/client")
        }
        server {
            runDirectory = file("run/server")
        }
    }

    //https://gist.github.com/maityyy/3dbcd558d58a6412c3a2a38c72706e8e
    afterEvaluate {
        loom.runs.configureEach {
            jvmArguments.addAll(["-XX:+IgnoreUnrecognizedVMOptions", "-XX:+AllowEnhancedClassRedefinition"])
            jvmArguments.add("-javaagent:${ configurations.compileClasspath.find { it.name.contains("sponge-mixin") } }")

            systemProperties.put("mixin.debug.export", "true")
        }
    }
}

loom.mods.register(mod_id) {
    sourceSet project.sourceSets.main
}

processResources {
    def map = [
            "version": project.version,
            "mod_id": mod_id,
            "minecraft_version": minecraft_version,
            "loader_version": libs.fabric.loader.get().version,
            "fabric_version": libs.fabric.api.get().version,
            "pulsar_version": libs.pulsar.get().version
    ]
    inputs.properties(map)
    filteringCharset = "UTF-8"

    filesMatching("fabric.mod.json") {
        expand map
    }
}

tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${mod_id}" }
    }
}

sourcesJar {
    exclude {
        sourceSets.main.allSource.contains it.file
    }
    from delombok
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = "${mod_id}-${loader_id}"
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    if (!local) {
        repositories {
            maven {
                name = "GitHubPackages"
                url = "https://maven.pkg.github.com/constellation-mc/flight-panel"
                credentials {
                    username = System.getenv("GITHUB_ACTOR")
                    password = System.getenv("GITHUB_TOKEN")
                }
            }
        }
    }
}

publishMods {
    file = remapJar.archiveFile
    additionalFiles.from(remapSourcesJar.archiveFile)
    version = "${mod_version}+mc${minecraft_version}+${loader_id}"

    changelog = file("CHANGELOG.md").text
    type = ReleaseType.valueOf(providers.environmentVariable("VERSION_TYPE").getOrElse("BETA"))
    modLoaders.add(loader_id)

    displayName = "${mod_version} (${minecraft_version})"

    modrinth {
        projectId = "XXXXXX"
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersions.add("${minecraft_version}")
        environment = CLIENT_ONLY

        requires("fabric-api")
        requires("pulsar")
    }
    curseforge {
        projectId = "XXXXXX"
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        minecraftVersions.add("${minecraft_version}")
        client = true
        server = false

        requires("fabric-api")
        requires("pulsar")
    }
    github {
        repository = "constellation-mc/flight-panel"
        accessToken = providers.environmentVariable("GITHUB_TOKEN")
        commitish = providers.environmentVariable("GITHUB_SHA").getOrElse("${minecraft_version}-${loader_id}")

        type = STABLE
    }

    dryRun = local
}